// automatically generated by the FlatBuffers compiler, do not modify

package edu.vanderbilt.edgent.types;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class TopicConnector extends Table {
  public static TopicConnector getRootAsTopicConnector(ByteBuffer _bb) { return getRootAsTopicConnector(_bb, new TopicConnector()); }
  public static TopicConnector getRootAsTopicConnector(ByteBuffer _bb, TopicConnector obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public TopicConnector __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String ebId() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer ebIdAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public String ebAddress() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer ebAddressAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public int receivePort() { int o = __offset(8); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int sendPort() { int o = __offset(10); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int controlPort() { int o = __offset(12); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createTopicConnector(FlatBufferBuilder builder,
      int ebIdOffset,
      int ebAddressOffset,
      int receivePort,
      int sendPort,
      int controlPort) {
    builder.startObject(5);
    TopicConnector.addControlPort(builder, controlPort);
    TopicConnector.addSendPort(builder, sendPort);
    TopicConnector.addReceivePort(builder, receivePort);
    TopicConnector.addEbAddress(builder, ebAddressOffset);
    TopicConnector.addEbId(builder, ebIdOffset);
    return TopicConnector.endTopicConnector(builder);
  }

  public static void startTopicConnector(FlatBufferBuilder builder) { builder.startObject(5); }
  public static void addEbId(FlatBufferBuilder builder, int ebIdOffset) { builder.addOffset(0, ebIdOffset, 0); }
  public static void addEbAddress(FlatBufferBuilder builder, int ebAddressOffset) { builder.addOffset(1, ebAddressOffset, 0); }
  public static void addReceivePort(FlatBufferBuilder builder, int receivePort) { builder.addInt(2, receivePort, 0); }
  public static void addSendPort(FlatBufferBuilder builder, int sendPort) { builder.addInt(3, sendPort, 0); }
  public static void addControlPort(FlatBufferBuilder builder, int controlPort) { builder.addInt(4, controlPort, 0); }
  public static int endTopicConnector(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

