// automatically generated by the FlatBuffers compiler, do not modify

package edu.vanderbilt.edgent.types;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class TopicCommand extends Table {
  public static TopicCommand getRootAsTopicCommand(ByteBuffer _bb) { return getRootAsTopicCommand(_bb, new TopicCommand()); }
  public static TopicCommand getRootAsTopicCommand(ByteBuffer _bb, TopicCommand obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public TopicCommand __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int type() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public ContainerCommand containerCommand() { return containerCommand(new ContainerCommand()); }
  public ContainerCommand containerCommand(ContainerCommand obj) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createTopicCommand(FlatBufferBuilder builder,
      int type,
      int containerCommandOffset) {
    builder.startObject(2);
    TopicCommand.addContainerCommand(builder, containerCommandOffset);
    TopicCommand.addType(builder, type);
    return TopicCommand.endTopicCommand(builder);
  }

  public static void startTopicCommand(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addType(FlatBufferBuilder builder, int type) { builder.addInt(0, type, 0); }
  public static void addContainerCommand(FlatBufferBuilder builder, int containerCommandOffset) { builder.addOffset(1, containerCommandOffset, 0); }
  public static int endTopicCommand(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishTopicCommandBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

