// automatically generated by the FlatBuffers compiler, do not modify

package edu.vanderbilt.edgent.types;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class WorkerCommand extends Table {
  public static WorkerCommand getRootAsWorkerCommand(ByteBuffer _bb) { return getRootAsWorkerCommand(_bb, new WorkerCommand()); }
  public static WorkerCommand getRootAsWorkerCommand(ByteBuffer _bb, WorkerCommand obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public WorkerCommand __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int type() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public edu.vanderbilt.edgent.types.TopicConnector topicConnector() { return topicConnector(new edu.vanderbilt.edgent.types.TopicConnector()); }
  public edu.vanderbilt.edgent.types.TopicConnector topicConnector(edu.vanderbilt.edgent.types.TopicConnector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createWorkerCommand(FlatBufferBuilder builder,
      int type,
      int topicConnectorOffset) {
    builder.startObject(2);
    WorkerCommand.addTopicConnector(builder, topicConnectorOffset);
    WorkerCommand.addType(builder, type);
    return WorkerCommand.endWorkerCommand(builder);
  }

  public static void startWorkerCommand(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addType(FlatBufferBuilder builder, int type) { builder.addInt(0, type, 0); }
  public static void addTopicConnector(FlatBufferBuilder builder, int topicConnectorOffset) { builder.addOffset(1, topicConnectorOffset, 0); }
  public static int endWorkerCommand(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishWorkerCommandBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

