---
- include: set_ansible_ssh_host.yml

- hosts: all
  gather_facts: False
  tasks:
    - name: copy remote files
      synchronize: src={{src_dir}} dest={{dest_dir}} mode=pull
      ignore_errors: true
