---
- include: set_ansible_ssh_host.yml

- hosts: all
  gather_facts: False
  tasks:
  - name: kill process
    command: pkill -fc "{{ item }}"
    register: res 
    failed_when: res.rc > 1 
    with_items: "pattern.split(',')"
