---
- include: set_ansible_ssh_host.yml

- hosts: all
  gather_facts: False
  become: True
  tasks:
    - name: reboot instance 
      command: /sbin/shutdown -r +1
      async: 0
      poll: 0
      ignore_errors: true
